apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
     env: dev
     fnc: db
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
     env: dev
     fnc: db
spec:
  selector:
    env: dev
    fnc: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: litesunstoneapi
  labels:
     env: dev
     fnc: api
spec:
  containers:
  - name: litesunstone
    image: zhuyunjie0207/litesunstone:latest
    env: 
      - name: DB_CONNECTION
        value: "mongodb://10.106.249.113:27017"
    ports:
    - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
     env: dev
     fnc: api
spec:
  selector:
    env: dev
    fnc: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000